USE aaa_word;

CREATE TABLE IF NOT EXISTS item_notes (
  id         BIGINT AUTO_INCREMENT PRIMARY KEY,
  item_type  VARCHAR(16) NOT NULL,
  item_text  VARCHAR(80) NOT NULL,
  note       TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_item_note (item_type, item_text)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
